name: norrenberger_assesment
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  dio: ^5.7.0
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  overlay_support: ^2.1.0
  either_dart: ^1.0.0
  pretty_dio_logger: ^1.4.0
  modal_bottom_sheet: ^3.0.0
  fluttertoast: ^8.2.8
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  lottie: ^3.1.3
  pinput: ^5.0.0
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/png/
    - assets/lottie/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
#  fonts:
#    - family: Montserrat
#      fonts:
#        - asset: assets/fonts/Montserrat-Black.ttf
#        - asset: assets/fonts/Montserrat-BlackItalic.ttf
#        - asset:
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
